version: '3.8'

services:
  db:
    image: mysql:8.1
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: db_filmes
      MYSQL_USER: usuario
      MYSQL_PASSWORD: usuario123
    volumes:
      - vol_dados_filmes:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  vol_dados_filmes: